using EnvDTE;
using Microsoft.VisualStudio.OLE.Interop;
using Microsoft.VisualStudio.Shell;
using System;
using System.ComponentModel;
using System.ComponentModel.Design.Serialization;
using System.IO;
using System.Windows.Forms;

namespace MattDavies.TortoiseGitToolbar.Config
{

  public static partial class GlobalConfig
  {
    // enabled when the user knows that the solution directory is not
    // trustworthy and the Active File path should be used in place of it
    // where applicable. Typically if the source files are known to not exist
    // as a child to the current solution.
    public static bool PreferFileOverSolution { get; set; } = false;
    public const string ExtensionName = "Tortoise Git Toolbar";
  }

  public class SettingsDialog : DialogPage
  {

    private static SettingsDialog _instance { get; set; } = new SettingsDialog();
    public SettingsDialog Instance() => _instance;

    [Category("Paths and Directories")]
    [DisplayName("Prefer File over Solution")]
    [Description("Enable this option if you know your source files will not exist within the solution directory. Useful" +
      " for when using generated solution files like the ones generated by CMake. ")]
    public bool RootDirectory
    {
      get { return GlobalConfig.PreferFileOverSolution; }
      set { GlobalConfig.PreferFileOverSolution = value; }
    }
  }
}